### ISSUE TITLE
ALLEGRO_OPENGL_MAJOR_VERSION and ALLEGRO_OPENGL_MINOR_VERSION do not work

### ISSUE THREAD

**Issue by bigov** [liballeg/allegro5#948]
The function al_create_display() set OpenGL context only witn 3.0 version, or the most current version. Parameters ALLEGRO_OPENGL_MAJOR_VERSION and ALLEGRO_OPENGL_MINOR_VERSION do not work.
It has to do with the _al_get_suggested_display_option function possibly returning the wrong values. The problem is discussed on [allegro.cc](https://www.allegro.cc/forums/thread/617591/1039688)

**Comment by EdgarReynaldo** [comment]
There are 2 bugs that I have found. One is expecting the value (1 << option) where option is 33 or 34 to have meaning. The other is that glGetString(GL_EXTENSIONS) is returning null.
https://www.allegro.cc/forums/thread/617591/1039695#target

**Comment by bigov** [comment]
This does not change anything. In this place, we simply try to help developers locate a possible bug in the library's code.

**Comment by EdgarReynaldo** [comment]
I have successfully requested and created a 3.2 context. But there are further problems with allegro's _al_glGetStringi function pointer. It is null, so neither print_extensions((const char*)glGetString(GL_EXTENSIONS)) nor print_extensions_3_0 using glGetStringi works.

https://www.allegro.cc/forums/thread/617591/1039711#target

**Comment by dos1** [comment]
Well, of course it's null there - the comment that's already there even says so.

Depending on `glGetString` in this place is one of the many things that make Allegro depend on Compatibility Profile contexts.

I'm still not sure what exactly is the problem that's being discussed here.

**Comment by fatcerberus** [comment]
From what I can tell it seems like @bigov expects to always get the exact version of OpenGL requested, rather than “requested or any later version”.

**Comment by dos1** [comment]
I'm not sure Allegro can do that at all.

From WGL spec:

> The attribute names WGL_CONTEXT_MAJOR_VERSION_ARB and WGL_CONTEXT_MINOR_VERSION_ARB request an OpenGL context supporting the specified version of the API. If successful, the context returned must be backwards compatible with the context requested.

AFAIR it was the same for GLX, and it's likely the same in NSOpenGL and EGL as well.

**Comment by EdgarReynaldo** [comment]
I'm telling you, there is a bug. Before, the branch that would have asked for an explicit version would never be visisted. It would always return the newest context available. I'm in the middle of fixing it so that _al_ogl_manage_extensions doesn't crash.

**Comment by EdgarReynaldo** [comment]
This affects X as well, I will make a further patch once I can test this on Ubuntu.

**Comment by EdgarReynaldo** [comment]
https://github.com/EdgarReynaldo/allegro5/pull/1

**Comment by fatcerberus** [comment]
@EdgarReynaldo Is there any reason you opened that pull against your own fork rather than the main repo?

**Comment by dos1** [comment]
Also, doesn't that patch break OpenGL < 3.0 contexts? Remember that due to its reliance on compatibility profiles, Allegro is still limited to OpenGL 2.1 on macOS.

**Comment by EdgarReynaldo** [comment]
Lol I have no idea, it was just the cleanest way for me to keep master synced with allegro.

glGetStringi is valid on < 3 afaik, the function is a misnomer ( print_extensions_3_0 ) .

**Comment by EdgarReynaldo** [comment]
>Is there any reason you opened that pull against your own fork rather than the main repo?

It's to prevent extra commits

**Comment by dos1** [comment]
`glGetStringi` was introduced in OpenGL 3.0.

**Comment by EdgarReynaldo** [comment]
This says core since 1.0 : https://www.khronos.org/opengl/wiki/GLAPI/glGetString, but of course there is no separate entry for glGetStringi so if they have some history I don't know. And you can always pre test glGetString(GL_EXTENSIONS) for null, to see if its available. I can modify the patch.

**Comment by fatcerberus** [comment]
This is why I prefer the manpage-style docs over the wiki:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml

**Comment by EdgarReynaldo** [comment]
Well, that actually lists the versions, which is far preferable. So yeah, I'll change things up and submit a new pull request.

**Comment by EdgarReynaldo** [comment]
Adjusted the pull request. It *should* handle contexts < 3 now.

**Comment by EdgarReynaldo** [comment]
Now it doesn't handle OPENGLES, let me fix it first.

**Comment by EdgarReynaldo** [comment]
Can someone review my pull request please? It's been sitting here for a month.

**Comment by SiegeLord** [comment]
Err, you made the pull request on your own repository... it needs to be made on this repository for us to notice it :).

**Comment by EdgarReynaldo** [comment]
Nevermind, I should have it fixed now, sorry about that. New to this thing a ma jiggy.

**Comment by EdgarReynaldo** [comment]
https://github.com/liballeg/allegro5/pull/969

**Comment by SiegeLord** [comment]
I guess this is fixed by https://github.com/liballeg/allegro5/pull/1021.

**Comment by dos1** [comment]
AFAIR it still happens on macOS (and gp2xwiz if anyone cares).

**Comment by SiegeLord** [comment]
Thanks, reopening!
